# Generated by Django 5.1.6 on 2025-02-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Entity Name')),
                ('entity_number', models.CharField(max_length=32, unique=True, verbose_name='Entity Number')),
                ('entity_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='Entity Type')),
                ('child_entities', models.ManyToManyField(blank=True, related_name='children', to='core.entityinformation')),
                ('parent_entities', models.ManyToManyField(blank=True, related_name='parents', to='core.entityinformation')),
            ],
            options={
                'verbose_name': 'Billed Entity',
                'verbose_name_plural': 'Billed Entities',
                'ordering': ('entity_number',),
            },
        ),
    ]
